Traceback (most recent call last):
  File "C:/Users/Davi/Desktop/MyPythonScripts/debbuging_test.py", line 36, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
